services:
  relaxinghippoquestsdatabase:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
  relaxinghippoquestsserver:
    depends_on:
      relaxinghippoquestsdatabase:
        condition: service_healthy
    environment:
      DB_HOST: relaxinghippoquestsserver
    build: "./server"
    ports:
      - 4000:4000
    volumes:
      - ./server/src:/app/src
