version: '3.9'

services:
  tournament-database:
    image: postgres:latest
    restart: 'no'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: tournament
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin -d tournament']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5435:5432
    expose:
      - 5432
    volumes:
      - tournament-database:/var/lib/postgresql/data

  tournament-server:
    depends_on:
      tournament-database:
        condition: service_healthy
    build: './server'
    ports:
      - 4000:4000
    volumes:
      - ./server/src:/app/src

  tournament-upload-service:
    build: file-upload-service
    ports:
      - 8000:8000
    volumes:
      - ./file-upload-service/files:/app/files

volumes:
  tournament-database:
