version: '3.9'

services:
  seekplayersdatabase:
    container_name: seekplayersdatabase
    hostname: seekplayersdatabase
    image: postgres:latest
    restart: 'no'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: seekplayers
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin -d seekplayers']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5435:5432
    expose:
      - 5432
    volumes:
      - seekplayersdatabase:/var/lib/postgresql/data

  seekplayersserver:
    depends_on:
      seekplayersdatabase:
        condition: service_healthy
    build: './server'
    ports:
      - 4000:4000
    volumes:
      - ./server/src:/app/src

  seekplayers-upload-service:
    build: file-upload-service
    ports:
      - 8000:8000
    volumes:
      - ./file-upload-service/files:/app/files

volumes:
  seekplayersdatabase:
