name: vps-deploy

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  deploy:
    needs: publish
    name: deploy image in remote vps
    runs-on: ubuntu-latest

    steps:
      - name: SSH into remote server and deploy
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.REMOTE_SSH_HOST }}
          username: ${{ secrets.REMOTE_SSH_USER }}
          password: ${{ secrets.REMOTE_SSH_PASSWORD }}
          port: 22
          script: |
            cd ${{ secrets.REMOTE_WORKING_DIRECTORY }}
            ./deploy-production.sh
